version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "maven"
      - "update"
    commit-message:
      prefix: "chore(deps):"
    reviewers:
      - username: "reviewer1"
        # Add more reviewers as needed
    assignees:
      - username: "assignee1"
        # Add more assignees as needed
    open-pull-requests-limit: 5
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"
        security-updates: true
    labels:
      - "security"
    commit-message:
      prefix: "fix(deps):"
